version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY1= "AIzaSyBPF4LoUPYTmDf1KMlNNIOqwUoPqGQstpA"#"AIzaSyBPF4LoUPYTmDf1KMlNNIOqwUoPqGQstpA"
      - GOOGLE_API_KEY2="AIzaSyDaorlbPkHLfp4-kucNiyJ3qUtrxIt4yqM"
      - HUGGINGFACEHUB_API_TOKEN="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"
    # Assure-toi que tu as le bon chemin pour ton application
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
